FROM node:20-alpine

WORKDIR /app

# Copy full monorepo
COPY . .

# Install deps only for this service
RUN npm install --workspace=src/services/notification-service

# Build
RUN npm run build --workspace=src/services/notification-service

EXPOSE 4004

CMD ["node", "src/services/notification-service/dist/server.js"]