FROM node:20-alpine

WORKDIR /app

# Copy full monorepo
COPY . .

# Install deps only for this service
RUN npm install --workspace=src/services/incident-service

# Build
RUN npm run build --workspace=src/services/incident-service

EXPOSE 4001

CMD ["node", "src/services/incident-service/dist/server.js"]
